// Code generated by "stringer -type Instruction"; DO NOT EDIT.

package svgpath

import "strconv"

const _Instruction_name = "ArcToCurveToHorizLineToLineToMoveToQuadCurveToSmoothCurveToSmoothQuadCurveToVertLineToClosePathArcToRelCurveToRelHorizLineToRelLineToRelMoveToRelQuadCurveToRelSmoothCurveToRelSmoothQuadCurveToRelVertLineToRelClosePathRel"

var _Instruction_map = map[Instruction]string{
	65:  _Instruction_name[0:5],
	67:  _Instruction_name[5:12],
	72:  _Instruction_name[12:23],
	76:  _Instruction_name[23:29],
	77:  _Instruction_name[29:35],
	81:  _Instruction_name[35:46],
	83:  _Instruction_name[46:59],
	84:  _Instruction_name[59:76],
	86:  _Instruction_name[76:86],
	90:  _Instruction_name[86:95],
	97:  _Instruction_name[95:103],
	99:  _Instruction_name[103:113],
	104: _Instruction_name[113:127],
	108: _Instruction_name[127:136],
	109: _Instruction_name[136:145],
	113: _Instruction_name[145:159],
	115: _Instruction_name[159:175],
	116: _Instruction_name[175:195],
	118: _Instruction_name[195:208],
	122: _Instruction_name[208:220],
}

func (i Instruction) String() string {
	if str, ok := _Instruction_map[i]; ok {
		return str
	}
	return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
}
